# This is a boilerplate parameters config generated for pipeline 'train_model'
# using Kedro 0.18.1.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.18.1/kedro_project_setup/configuration.html#parameters

config: {
    "lr": 0.01,
    "momentum": 0.2,
    "step_size": 4,
    "gamma": 0.1
}
num_epochs: 10
gpus: 1
project: 'cats_and_dogs_segmentation'